local Event = require "libs.event"

local M = {}
M.LANGUAGE_CHANGED = Event("LANGUAGE_CHANGED")
M.WINDOW_RESIZED = Event("WINDOW_RESIZED")
M.STORAGE_CHANGED = Event("STORAGE_CHANGED")
M.WINDOW_EVENT = Event("WINDOW_EVENT")
M.MONEY_ADD = Event("MONEY_ADD")
M.MONEY_SPEND = Event("MONEY_SPEND")
M.EXP_ADD = Event("EXP_ADD")
M.LEVEL_CHANGED = Event("LEVEL_CHANGED")


M.RESOURCE_ADD = Event("RESOURCE_ADD")
M.RESOURCE_SPEND = Event("RESOURCE_SPEND")

return M